export const FETCH_LIST_OF_TOPICS = 'FETCH_LIST_OF_TOPICS'
export const FETCH_LIST_OF_TOPICS_SUCCESS = 'FETCH_LIST_OF_TOPICS_SUCCESS'

export const UPDATE_SELECTED_TOPIC = 'UPDATE_SELECTED_TOPIC'

export const RESET_VIEW_LAYOUT = 'RESET_VIEW_LAYOUT'
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS'
