export const CONSUME_MESSAGE_REQUEST = 'CONSUME_MESSAGE_REQUEST'
export const CONSUME_MESSAGE_SUCCESS = 'CONSUME_MESSAGE_SUCCESS'

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const UPDATE_CONSUME_MESSAGE = 'UPDATE_CONSUME_MESSAGE'
