export const CONSUME_MESSAGE_REQUEST = 'CONSUME_MESSAGE_REQUEST'
export const CONSUME_MESSAGE_SUCCESS = 'CONSUME_MESSAGE_SUCCESS'

export const UPDATE_CONSUME_MESSAGE = 'UPDATE_CONSUME_MESSAGE'
export const FILTER_MESSAGE = 'FILTER_MESSAGE'
export const RESET_MESSAGES = 'RESET_MESSAGES'

export const CONNECT_SUCCESS = 'CONNECT_SUCCESS'
export const UPDATE_NUMBER_OF_MESSAGES = 'UPDATE_NUMBER_OF_MESSAGES'
