export const PUBLISH_MESSAGE_REQUEST = 'PUBLISH_MESSAGE_REQUEST'
export const PUBLISH_MESSAGE_SUCCESS = 'PUBLISH_MESSAGE_SUCCESS'

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const UPDATE_PUBLISH_MESSAGE = 'UPDATE_PUBLISH_MESSAGE'
