export const FETCH_CONNECTIONS = 'FETCH_CONNECTIONS'
export const FETCH_CONNECTIONS_SUCCESS = 'FETCH_CONNECTIONS_SUCCESS'

export const OPEN_CONNECTIONS = 'OPEN_CONNECTIONS'

export const DELETE_CONNECTION_SUCCESS = 'DELETE_CONNECTION_SUCCESS'
export const ADD_CONNECTION_SUCCESS = 'ADD_CONNECTION_SUCCESS'
