export const FETCH_CONNECTIONS = 'FETCH_CONNECTIONS'
export const FETCH_CONNECTIONS_SUCCESS = 'FETCH_CONNECTIONS_SUCCESS'

export const OPEN_CONNECTIONS = 'OPEN_CONNECTIONS'

export const ADD_CONNECTION = 'ADD_CONNECTION'
export const ADD_CONNECTION_SUCCESS = 'ADD_CONNECTION_SUCCESS'

export const API_FAILURE = 'API_FAILURE'

export const FETCH_LIST_OF_TOPICS = 'FETCH_LIST_OF_TOPICS'
export const FETCH_LIST_OF_TOPICS_SUCCESS = 'FETCH_LIST_OF_TOPICS_SUCCESS'

export const UPDATE_SELECTED_TOPIC = 'UPDATE_SELECTED_TOPIC'
