name: Visual Kafka Build

push:
  branches:
    - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.14, windows-2019, ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: yarn install
        run: |
          yarn install

      - name: Packaging Application for MacOS
        env:
          GITHUB_TOKEN: ${{ secrets.VISUAL_KAFKA_GITHUB_TOKEN }}
        if: startsWith(matrix.os, 'macos-10.14')
        run: |
          yarn package-ci
          yarn lint
          yarn flow
          yarn build-e2e

      - name: Packaging Application for Windows
        env:
          GITHUB_TOKEN: ${{ secrets.VISUAL_KAFKA_GITHUB_TOKEN }}
        if: startsWith(matrix.os, 'windows-2019')
        run: |
          yarn package-ci
          yarn lint
          yarn build-e2e

      - name: Packaging Application for Ubuntu
        env:
          GITHUB_TOKEN: ${{ secrets.VISUAL_KAFKA_GITHUB_TOKEN }}
        if: startsWith(matrix.os, 'ubuntu-18.04')
        run: |
          yarn package-ci
          yarn lint
          yarn flow
          yarn build-e2e
